### ISSUE TITLE
Fitting failed in Xray calibration

### ISSUE THREAD

**Issue by pohsun** [psi46/MoReWeb#108] opened 2015-08-03 08:46 UTC
Hi,
      I got a strange fit result and there's no obvious clue in the plot (Xray/q_Sn_C12_V0). Could you help me checking how this happens? The output root file is put in lxplus:~pchen/public/psi46/MoReWeb/issue108/pxar_Sn.root.

Thanks,
Po-Hsun

![fluorescencetarget](https://cloud.githubusercontent.com/assets/4365744/9033379/c04eb87e-39c6-11e5-97d9-7c23976ad5d5.jpg)

**Comment by piberger** [comment] 2015-08-03 12:21
Hi Po-Hsun,

this seems to be the same problem than #80 , try setting

    SpectrumFitImproveInitialGuess: True
    SpectrumFitAdditionalConstraints: True

in global.cfg https://github.com/psi46/MoReWeb/blob/master/Analyse/Configuration/Software/global.cfg#L21

**Comment by piberger** [comment] 2015-09-23 08:41
can I close this issue or does the problem still exists?

**Comment by ywkao** [comment] 2015-10-15 10:29
Hi,
I have checked the fit result with the new setting. The problem is indeed fixed!! However, this is only for our local part. The result on DB [1] is still the same...

[1] http://cmspixelprod.pi.infn.it/data/pixelslocal/OUT/GLOBAL/M3010/prod-HR-17Sept15a-refit/REV001/R001/M3010_XRayHRQualification_2015-10-05_17h08m_1444057696/QualificationGroup/XrayCalibrationSpectrum_1/Chips_Xray/Chip_Xray12/TestResult.html

**Comment by piberger** [comment] 2015-10-15 12:47
Hi, 
thanks for the feedback, results in DB will be reprocessed soon, but I don't know when exactly and it will take some time to process all modules :-)

**Closed by piberger** 2015-10-15 12:47 UTC

**Comment by ywkao** [comment] 2015-10-15 13:37
OK, I see. Thank you!!
