### ISSUE TITLE
Column uniformity issue in HighRate test

### ISSUE THREAD

**Issue by ywkao** [psi46/MoReWeb#111] opened 2015-08-27 07:34 UTC
Hi,
In X-ray high-rate efficiency test, some modules would get grade C purely due to their poor column uniformity. When investigating into this problem, we find it is simply an issue related to hot pixels (as we mask all the hot pixels and redo the test, these modules get grade A in the end).

Below shows three plots coming from the previous testing result of M3019 chip3. Two of them are the hit maps with different hit rates[1][2], and the other is the uniformity ratio[3]. Since the overall quality of a testing module should not depend on only two or three hot pixels, I am wondering if MoReWeb could identify out those hot pixels on hit maps and remove their contributions so that it could correct the uniformity problem automatically.

Thanks,
Yu-Wei

[1] Hit map with high hit rate
![hitmap150](https://cloud.githubusercontent.com/assets/11542148/9514851/f108c24a-4ccf-11e5-9af0-caccfba73bb3.png)

[2] Hit map with low hit rate
![hitmap50](https://cloud.githubusercontent.com/assets/11542148/9514855/f5990d92-4ccf-11e5-8e75-376b6b995add.png)

[3] Column uniformity ratio per column
![columnuniformitypercolumn](https://cloud.githubusercontent.com/assets/11542148/9514616/32ddd5fe-4cce-11e5-9f21-9d125d036bf5.png)

**Comment by piberger** [comment] 2015-09-02 16:50
Hi Yu-Wei,

in principle I think we should mask (or re-trim) all hot pixels during the test, since they influence the whole double column.
Even if these single pixels would be taken out in the analysis, the uniformity problems could remain due to decreased efficiency of the whole double column. The efficiency measurement would suffer, too.

Are you doing any of the mask/re-trim tests?
We are doing the hotpixel re-trimming test in pXar under a rate of roughly 150 MHz/cm2 and this seems to work quite well. For all ~50 modules we tested we only had this hotpixel problem once for one single hot-pixel that "suddenly appeared" for one of the rates. We re-tested the module and it worked in the 2nd attempt.

If it is not possible for you to re-test the modules, I could try to add an option to MoReWeb to filter out these pixels from this test. (Even if the uniformity is not ideal then, it might help to "shift" the grading to A)

**Comment by starodum** [comment] 2015-09-02 17:10
Hi Pirmin,
I disagree with your last proposal. In such cases the hot pixels should be masked and the test repeated. We can not introduce solution that "might help".

**Comment by ywkao** [comment] 2015-09-03 10:28
Hi,

I totally agree that we should mask/re-trim all hot pixels during the test. My original intention is whether I could simply mask these hot pixels without repeating the whole HR efficiency test once I miss any one of hot pixels during the test.

Yes, I am doing the mask test in pXar in the beginning of the tests. But since it does not always mask all the hot pixels, I would check the hitmaps carefully everytime before the HR tests now. The suggestion of the re-trim tests sounds good. I would try that first!

Thank you very much!
Yu-Wei

**Comment by simonspa** [comment] 2015-09-03 11:04
as @starodum said, the problem is that a hot pixel will heavily influence the behavior of the chip *at data acquisition time* and thus masking it in the analysis will not help but just result in dubious results from the test.

**Comment by piberger** [comment] 2015-09-03 11:52
To get rid of hot-pixels we made a pXar test to re-adjust the trimbits of hot pixels because in almost all  cases the pixels are hot because of a not correct trim bit.
The test is called "highrate:trimhotpixels" and needs parameters "trimhotpixelthr=200,runsecondsHotPixels=1,savetrimbits=1,maskuntrimmable=1". The trimhotpixelthr parameter should be adjusted to the rate which you use (we use ~150 MHz/cm2), it's the maximum number of hits allowed for a pixel not be counted as hot pixel. 
We run this test once before all other HR tests and can get rid of hot pixels almost always.

**Comment by piberger** [comment] 2015-09-23 08:42
can I close this?

**Comment by ywkao** [comment] 2015-09-25 18:00
Yes, thank you very much!!

**Closed** 2015-09-29 07:42 UTC
